### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by hako** [hako/bbcli#9]
Running bbcli in Python 3 gets us this:
```
Traceback (most recent call last):
  File "/usr/bin/bbcli", line 7, in <module>
    from bbcli.core import live
  File "/usr/lib/python3.4/site-packages/bbcli/core.py", line 158
    print "Keyboard interrupt received, quitting gracefully"
```
Need to get around doing this soon before [2020](https://pythonclock.org/)

**Comment by hako** [comment]
Closed due to #10 Python 3 is now supported!
